<a href="https://colab.research.google.com/github/jacculpo/preprocess_lending_club_data/blob/master/Catch_all_stats_for_each_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Application Test Data:**

Main table, borken into two files for Training (with TARGET), and Testing (Without Target)

## **Important Notes -**

Static data for all applications. One row represents one loan in our data sample.

• CNT stands for “count”, like CNT_CHILDREN

• AMT stands for “amount”, mostly use for monetary

• FLAG stands for boolean with 1 is yes. FLAG_DOCUMENT means loan applicant have to submit some documents like income proof, and this flag customer actual submitted or not.

• OBS stands for “observation”, also means “is it time for?”.

• DEF stands for “actual default”.

• Different between OBS and DEF (like OBS_30_CNT_SOCIAL_CIRCLE) is that OBS is flagging “is it time for that event to be eligible to happen”, while DEF is that “is it eligible to happen AND actually happened”.

• DAYS stands for “number of days”

• NUM stands for “sequence number”

• x-sell means customers already evaluated risk by previous loans (loans in HC even before previous_application), before giving the loan. This is very valuable feature.

• walk in means this is new customer as this is his first time loan

## **Shape**

(48744, 121)

## **Column Names and Null Value Counts**

Column SK_ID_CURR: 0 null values

Column NAME_CONTRACT_TYPE: 0 null values

Column CODE_GENDER: 0 null values

Column FLAG_OWN_CAR: 0 null values

Column FLAG_OWN_REALTY: 0 null values

Column CNT_CHILDREN: 0 null values

Column AMT_INCOME_TOTAL: 0 null values

Column AMT_CREDIT: 0 null values

Column AMT_ANNUITY: 24 null values

Column AMT_GOODS_PRICE: 0 null values

Column NAME_TYPE_SUITE: 911 null values

Column NAME_INCOME_TYPE: 0 null values

Column NAME_EDUCATION_TYPE: 0 null values

Column NAME_FAMILY_STATUS: 0 null values

Column NAME_HOUSING_TYPE: 0 null values

Column REGION_POPULATION_RELATIVE: 0 null values

Column DAYS_BIRTH: 0 null values

Column DAYS_EMPLOYED: 0 null values

Column DAYS_REGISTRATION: 0 null values

Column DAYS_ID_PUBLISH: 0 null values

Column OWN_CAR_AGE: 32312 null values

Column FLAG_MOBIL: 0 null values

Column FLAG_EMP_PHONE: 0 null values

Column FLAG_WORK_PHONE: 0 null values

Column FLAG_CONT_MOBILE: 0 null values

Column FLAG_PHONE: 0 null values

Column FLAG_EMAIL: 0 null values

Column OCCUPATION_TYPE: 15605 null values

Column CNT_FAM_MEMBERS: 0 null values

Column REGION_RATING_CLIENT: 0 null values

Column REGION_RATING_CLIENT_W_CITY: 0 null values

Column WEEKDAY_APPR_PROCESS_START: 0 null values

Column HOUR_APPR_PROCESS_START: 0 null values

Column REG_REGION_NOT_LIVE_REGION: 0 null values

Column REG_REGION_NOT_WORK_REGION: 0 null values

Column LIVE_REGION_NOT_WORK_REGION: 0 null values

Column REG_CITY_NOT_LIVE_CITY: 0 null values

Column REG_CITY_NOT_WORK_CITY: 0 null values

Column LIVE_CITY_NOT_WORK_CITY: 0 null values

Column ORGANIZATION_TYPE: 0 null values

Column EXT_SOURCE_1: 20532 null values

Column EXT_SOURCE_2: 8 null values

Column EXT_SOURCE_3: 8668 null values

Column APARTMENTS_AVG: 23887 null values

Column BASEMENTAREA_AVG: 27641 null values

Column YEARS_BEGINEXPLUATATION_AVG: 22856 null values

Column YEARS_BUILD_AVG: 31818 null values

Column COMMONAREA_AVG: 33495 null values

Column ELEVATORS_AVG: 25189 null values

Column ENTRANCES_AVG: 23579 null values

Column FLOORSMAX_AVG: 23321 null values

Column FLOORSMIN_AVG: 32466 null values

Column LANDAREA_AVG: 28254 null values

Column LIVINGAPARTMENTS_AVG: 32780 null values

Column LIVINGAREA_AVG: 23552 null values

Column NONLIVINGAPARTMENTS_AVG: 33347 null values

Column NONLIVINGAREA_AVG: 26084 null values

Column APARTMENTS_MODE: 23887 null values

Column BASEMENTAREA_MODE: 27641 null values

Column YEARS_BEGINEXPLUATATION_MODE: 22856 null values

Column YEARS_BUILD_MODE: 31818 null values

Column COMMONAREA_MODE: 33495 null values

Column ELEVATORS_MODE: 25189 null values

Column ENTRANCES_MODE: 23579 null values

Column FLOORSMAX_MODE: 23321 null values

Column FLOORSMIN_MODE: 32466 null values

Column LANDAREA_MODE: 28254 null values

Column LIVINGAPARTMENTS_MODE: 32780 null values

Column LIVINGAREA_MODE: 23552 null values

Column NONLIVINGAPARTMENTS_MODE: 33347 null values

Column NONLIVINGAREA_MODE: 26084 null values

Column APARTMENTS_MEDI: 23887 null values

Column BASEMENTAREA_MEDI: 27641 null values

Column YEARS_BEGINEXPLUATATION_MEDI: 22856 null values

Column YEARS_BUILD_MEDI: 31818 null values

Column COMMONAREA_MEDI: 33495 null values

Column ELEVATORS_MEDI: 25189 null values

Column ENTRANCES_MEDI: 23579 null values

Column FLOORSMAX_MEDI: 23321 null values

Column FLOORSMIN_MEDI: 32466 null values

Column LANDAREA_MEDI: 28254 null values

Column LIVINGAPARTMENTS_MEDI: 32780 null values

Column LIVINGAREA_MEDI: 23552 null values

Column NONLIVINGAPARTMENTS_MEDI: 33347 null values

Column NONLIVINGAREA_MEDI: 26084 null values

Column FONDKAPREMONT_MODE: 32797 null values

Column HOUSETYPE_MODE: 23619 null values

Column TOTALAREA_MODE: 22624 null values

Column WALLSMATERIAL_MODE: 23893 null values

Column EMERGENCYSTATE_MODE: 22209 null values

Column OBS_30_CNT_SOCIAL_CIRCLE: 29 null values

Column DEF_30_CNT_SOCIAL_CIRCLE: 29 null values

Column OBS_60_CNT_SOCIAL_CIRCLE: 29 null values

Column DEF_60_CNT_SOCIAL_CIRCLE: 29 null values

Column DAYS_LAST_PHONE_CHANGE: 0 null values

Column FLAG_DOCUMENT_2: 0 null values

Column FLAG_DOCUMENT_3: 0 null values

Column FLAG_DOCUMENT_4: 0 null values

Column FLAG_DOCUMENT_5: 0 null values

Column FLAG_DOCUMENT_6: 0 null values

Column FLAG_DOCUMENT_7: 0 null values

Column FLAG_DOCUMENT_8: 0 null values

Column FLAG_DOCUMENT_9: 0 null values

Column FLAG_DOCUMENT_10: 0 null values

Column FLAG_DOCUMENT_11: 0 null values

Column FLAG_DOCUMENT_12: 0 null values

Column FLAG_DOCUMENT_13: 0 null values

Column FLAG_DOCUMENT_14: 0 null values

Column FLAG_DOCUMENT_15: 0 null values

Column FLAG_DOCUMENT_16: 0 null values

Column FLAG_DOCUMENT_17: 0 null values

Column FLAG_DOCUMENT_18: 0 null values

Column FLAG_DOCUMENT_19: 0 null values

Column FLAG_DOCUMENT_20: 0 null values

Column FLAG_DOCUMENT_21: 0 null values

Column AMT_REQ_CREDIT_BUREAU_HOUR: 6049 null values

Column AMT_REQ_CREDIT_BUREAU_DAY: 6049 null values

Column AMT_REQ_CREDIT_BUREAU_WEEK: 6049 null values

Column AMT_REQ_CREDIT_BUREAU_MON: 6049 null values

Column AMT_REQ_CREDIT_BUREAU_QRT: 6049 null values

Column AMT_REQ_CREDIT_BUREAU_YEAR: 6049 null values

# **Application Training Data:**

Main table, broken into two files for Training (with TARGET), and Testing (Without Target)

## **Important Notes -**

Static data for all applications. One row represents one loan in our data sample.

• CNT stands for “count”, like CNT_CHILDREN

• AMT stands for “amount”, mostly use for monetary

• FLAG stands for boolean with 1 is yes. FLAG_DOCUMENT means loan applicant have to submit some documents like income proof, and this flag customer actual submitted or not.

• OBS stands for “observation”, also means “is it time for?”.

• DEF stands for “actual default”.

• Different between OBS and DEF (like OBS_30_CNT_SOCIAL_CIRCLE) is that OBS is flagging “is it time for that event to be eligible to happen”, while DEF is that “is it eligible to happen AND actually happened”.

• DAYS stands for “number of days”

• NUM stands for “sequence number”

• x-sell means customers already evaluated risk by previous loans (loans in HC even before previous_application), before giving the loan. This is very valuable feature.

• walk in means this is new customer as this is his first time loan

## **Shape**

(307511, 122)

## **Column Names and Null Values**

Column SK_ID_CURR: 0 null values

Column TARGET: 0 null values

Column NAME_CONTRACT_TYPE: 0 null values

Column CODE_GENDER: 0 null values

Column FLAG_OWN_CAR: 0 null values

Column FLAG_OWN_REALTY: 0 null values

Column CNT_CHILDREN: 0 null values

Column AMT_INCOME_TOTAL: 0 null values

Column AMT_CREDIT: 0 null values

Column AMT_ANNUITY: 12 null values

Column AMT_GOODS_PRICE: 278 null values

Column NAME_TYPE_SUITE: 1292 null values

Column NAME_INCOME_TYPE: 0 null values

Column NAME_EDUCATION_TYPE: 0 null values

Column NAME_FAMILY_STATUS: 0 null values

Column NAME_HOUSING_TYPE: 0 null values

Column REGION_POPULATION_RELATIVE: 0 null values

Column DAYS_BIRTH: 0 null values

Column DAYS_EMPLOYED: 0 null values

Column DAYS_REGISTRATION: 0 null values

Column DAYS_ID_PUBLISH: 0 null values

Column OWN_CAR_AGE: 202929 null values

Column FLAG_MOBIL: 0 null values

Column FLAG_EMP_PHONE: 0 null values

Column FLAG_WORK_PHONE: 0 null values

Column FLAG_CONT_MOBILE: 0 null values

Column FLAG_PHONE: 0 null values

Column FLAG_EMAIL: 0 null values

Column OCCUPATION_TYPE: 96391 null values

Column CNT_FAM_MEMBERS: 2 null values

Column REGION_RATING_CLIENT: 0 null values

Column REGION_RATING_CLIENT_W_CITY: 0 null values

Column WEEKDAY_APPR_PROCESS_START: 0 null values

Column HOUR_APPR_PROCESS_START: 0 null values

Column REG_REGION_NOT_LIVE_REGION: 0 null values

Column REG_REGION_NOT_WORK_REGION: 0 null values

Column LIVE_REGION_NOT_WORK_REGION: 0 null values

Column REG_CITY_NOT_LIVE_CITY: 0 null values

Column REG_CITY_NOT_WORK_CITY: 0 null values

Column LIVE_CITY_NOT_WORK_CITY: 0 null values

Column ORGANIZATION_TYPE: 0 null values

Column EXT_SOURCE_1: 173378 null values

Column EXT_SOURCE_2: 660 null values

Column EXT_SOURCE_3: 60965 null values

Column APARTMENTS_AVG: 156061 null values

Column BASEMENTAREA_AVG: 179943 null values

Column YEARS_BEGINEXPLUATATION_AVG: 150007 null values

Column YEARS_BUILD_AVG: 204488 null values

Column COMMONAREA_AVG: 214865 null values

Column ELEVATORS_AVG: 163891 null values

Column ENTRANCES_AVG: 154828 null values

Column FLOORSMAX_AVG: 153020 null values

Column FLOORSMIN_AVG: 208642 null values

Column LANDAREA_AVG: 182590 null values

Column LIVINGAPARTMENTS_AVG: 210199 null values

Column LIVINGAREA_AVG: 154350 null values

Column NONLIVINGAPARTMENTS_AVG: 213514 null values

Column NONLIVINGAREA_AVG: 169682 null values

Column APARTMENTS_MODE: 156061 null values

Column BASEMENTAREA_MODE: 179943 null values

Column YEARS_BEGINEXPLUATATION_MODE: 150007 null values

Column YEARS_BUILD_MODE: 204488 null values

Column COMMONAREA_MODE: 214865 null values

Column ELEVATORS_MODE: 163891 null values

Column ENTRANCES_MODE: 154828 null values

Column FLOORSMAX_MODE: 153020 null values

Column FLOORSMIN_MODE: 208642 null values

Column LANDAREA_MODE: 182590 null values

Column LIVINGAPARTMENTS_MODE: 210199 null values

Column LIVINGAREA_MODE: 154350 null values

Column NONLIVINGAPARTMENTS_MODE: 213514 null values

Column NONLIVINGAREA_MODE: 169682 null values

Column APARTMENTS_MEDI: 156061 null values

Column BASEMENTAREA_MEDI: 179943 null values

Column YEARS_BEGINEXPLUATATION_MEDI: 150007 null values

Column YEARS_BUILD_MEDI: 204488 null values

Column COMMONAREA_MEDI: 214865 null values

Column ELEVATORS_MEDI: 163891 null values

Column ENTRANCES_MEDI: 154828 null values

Column FLOORSMAX_MEDI: 153020 null values

Column FLOORSMIN_MEDI: 208642 null values

Column LANDAREA_MEDI: 182590 null values

Column LIVINGAPARTMENTS_MEDI: 210199 null values

Column LIVINGAREA_MEDI: 154350 null values

Column NONLIVINGAPARTMENTS_MEDI: 213514 null values

Column NONLIVINGAREA_MEDI: 169682 null values

Column FONDKAPREMONT_MODE: 210295 null values

Column HOUSETYPE_MODE: 154297 null values

Column TOTALAREA_MODE: 148431 null values

Column WALLSMATERIAL_MODE: 156341 null values

Column EMERGENCYSTATE_MODE: 145755 null values

Column OBS_30_CNT_SOCIAL_CIRCLE: 1021 null values

Column DEF_30_CNT_SOCIAL_CIRCLE: 1021 null values

Column OBS_60_CNT_SOCIAL_CIRCLE: 1021 null values

Column DEF_60_CNT_SOCIAL_CIRCLE: 1021 null values

Column DAYS_LAST_PHONE_CHANGE: 1 null values

Column FLAG_DOCUMENT_2: 0 null values

Column FLAG_DOCUMENT_3: 0 null values

Column FLAG_DOCUMENT_4: 0 null values

Column FLAG_DOCUMENT_5: 0 null values

Column FLAG_DOCUMENT_6: 0 null values

Column FLAG_DOCUMENT_7: 0 null values

Column FLAG_DOCUMENT_8: 0 null values

Column FLAG_DOCUMENT_9: 0 null values

Column FLAG_DOCUMENT_10: 0 null values

Column FLAG_DOCUMENT_11: 0 null values

Column FLAG_DOCUMENT_12: 0 null values

Column FLAG_DOCUMENT_13: 0 null values

Column FLAG_DOCUMENT_14: 0 null values

Column FLAG_DOCUMENT_15: 0 null values

Column FLAG_DOCUMENT_16: 0 null values

Column FLAG_DOCUMENT_17: 0 null values

Column FLAG_DOCUMENT_18: 0 null values

Column FLAG_DOCUMENT_19: 0 null values

Column FLAG_DOCUMENT_20: 0 null values

Column FLAG_DOCUMENT_21: 0 null values

Column AMT_REQ_CREDIT_BUREAU_HOUR: 41519 null values

Column AMT_REQ_CREDIT_BUREAU_DAY: 41519 null values

Column AMT_REQ_CREDIT_BUREAU_WEEK: 41519 null values

Column AMT_REQ_CREDIT_BUREAU_MON: 41519 null values

Column AMT_REQ_CREDIT_BUREAU_QRT: 41519 null values

Column AMT_REQ_CREDIT_BUREAU_YEAR: 41519 null values

# **Bureau Balance**

Monthly balances of previous credits in Credit Bureau.

# **Important Notes -**

This table has one row for each month of history of every previous credit reported to Credit Bureau – i.e the table has (#loans in sample * # of relative previous credits * # of months where we have some history observable for the previous credits) rows.

Month of balance relative to application date (-1 means the freshest balance date)

C means closed, X means status unknown, 0 means no DPD, 1 means maximal did during month between 1-30, 2 means DPD 31-60,… 5 means DPD 120+ or sold or written off

# **Shape**

(27299925, 3)

# **Column Names and Null Values**

Column SK_ID_BUREAU: 0 null values

Column MONTHS_BALANCE: 0 null values

Column STATUS: 0 null values

# **Total Unique SK ID's**

817395

# **Bureau CSV**

All client's previous credits provided by other financial institutions that were reported to Credit Bureau (for clients who have a loan in our sample).

For every loan in our sample, there are as many rows as number of credits the client had in Credit Bureau before the application date.

These columns collectively provide a detailed view of a client's previous and ongoing credit obligations.

## **Important Notes -**

Currency 1: The account is "current" and up-to-date with payments. This means that there are no missed payments and the borrower is in good standing.

Currency 2: The account is one payment cycle past due. This typically means the payment is 30 days late.

Currency 3: The account is two payment cycles past due, usually indicating that the payment is 60 days late.



## **Shape**

(1716428, 17)

## **Column Names and Null Values**

Column SK_ID_CURR: 0 null values

Column SK_ID_BUREAU: 0 null values

Column CREDIT_ACTIVE: 0 null values

Column CREDIT_CURRENCY: 0 null values

Column DAYS_CREDIT: 0 null values

Column CREDIT_DAY_OVERDUE: 0 null values

Column DAYS_CREDIT_ENDDATE: 105553 null values

Column DAYS_ENDDATE_FACT: 633653 null values

Column AMT_CREDIT_MAX_OVERDUE: 1124488 null values

Column CNT_CREDIT_PROLONG: 0 null values

Column AMT_CREDIT_SUM: 13 null values

Column AMT_CREDIT_SUM_DEBT: 257669 null values

Column AMT_CREDIT_SUM_LIMIT: 591780 null values

Column AMT_CREDIT_SUM_OVERDUE: 0 null values

Column CREDIT_TYPE: 0 null values

Column DAYS_CREDIT_UPDATE: 0 null values

Column AMT_ANNUITY: 1226791 null values

# **Credit Card Balance**

## **Important Notes -**

Monthly balance snapshots of previous credit cards that the applicant has with Home Credit.

This table has one row for each month of history of every previous credit in Home Credit (consumer credit and cash loans) related to loans in our sample – i.e. the table has (#loans in sample * # of relative previous credit cards * # of months where we have some history observable for the previous credit card) rows.

These columns collectively provide a detailed view of a client’s credit card usage and payment behavior over time, which can be used to assess their financial habits and risk.

## **Shape**

(3840312, 23)

## **Column Names and Null Values**

Column SK_ID_PREV: 0 null values

Column SK_ID_CURR: 0 null values

Column MONTHS_BALANCE: 0 null values

Column AMT_BALANCE: 0 null values

Column AMT_CREDIT_LIMIT_ACTUAL: 0 null values

Column AMT_DRAWINGS_ATM_CURRENT: 749816 null values

Column AMT_DRAWINGS_CURRENT: 0 null values

Column AMT_DRAWINGS_OTHER_CURRENT: 749816 null values

Column AMT_DRAWINGS_POS_CURRENT: 749816 null values

Column AMT_INST_MIN_REGULARITY: 305236 null values

Column AMT_PAYMENT_CURRENT: 767988 null values

Column AMT_PAYMENT_TOTAL_CURRENT: 0 null values

Column AMT_RECEIVABLE_PRINCIPAL: 0 null values

Column AMT_RECIVABLE: 0 null values

Column AMT_TOTAL_RECEIVABLE: 0 null values

Column CNT_DRAWINGS_ATM_CURRENT: 749816 null values

Column CNT_DRAWINGS_CURRENT: 0 null values

Column CNT_DRAWINGS_OTHER_CURRENT: 749816 null values

Column CNT_DRAWINGS_POS_CURRENT: 749816 null values

Column CNT_INSTALMENT_MATURE_CUM: 305236 null values

Column NAME_CONTRACT_STATUS: 0 null values

Column SK_DPD: 0 null values

Column SK_DPD_DEF: 0 null values

# **Installment Payments**

## **Important Notes -**

Repayment history for the previously disbursed credits in Home Credit related to the loans in our sample.

There is a) one row for every payment that was made plus b) one row each for missed payment.

One row is equivalent to one payment of one installment OR one installment corresponding to one payment of one previous Home Credit credit related to loans in our sample.

Provide a comprehensive view of how clients manage their installment payments over time. This data is essential for understanding clients' payment behavior, such as whether they are making payments on time, paying the full amount, or delaying payments.

## **Shape**

(13605401, 8)

## **Column Names and Null Values**

Column SK_ID_PREV: 0 null values

Column SK_ID_CURR: 0 null values

Column NUM_INSTALMENT_VERSION: 0 null values

Column NUM_INSTALMENT_NUMBER: 0 null values

Column DAYS_INSTALMENT: 0 null values

Column DAYS_ENTRY_PAYMENT: 2905 null values

Column AMT_INSTALMENT: 0 null values

Column AMT_PAYMENT: 2905 null values

# **POS CASH BALANCE**

## **Important Notes -**

Monthly balance snapshots of previous POS (point of sales) and cash loans that the applicant had with Home Credit.

This table has one row for each month of history of every previous credit in
Home Credit (consumer credit and cash loans) related to loans in our sample – i.e. the table has (#loans in sample * # of relative previous credits * # of months in which we have some history observable for the previous credits) rows.

Monthly performance and status of POS or cash loans, including details on payment behavior, contract status, and overdue payments.

## **Shape**

(10001358, 8)

## **Column Names and Null Values**

Column SK_ID_PREV: 0 null values

Column SK_ID_CURR: 0 null values

Column MONTHS_BALANCE: 0 null values

Column CNT_INSTALMENT: 26071 null values

Column CNT_INSTALMENT_FUTURE: 26087 null values

Column NAME_CONTRACT_STATUS: 0 null values

Column SK_DPD: 0 null values

Column SK_DPD_DEF: 0 null values

# **Previous Applications**

## **Important Notes -**

All previous applications for Home Credit loans of clients who have loans in our sample.

There is one row for each previous application related to loans in our data sample.

## **Shape**

(1670214, 37)

## **Column Names and Null Values**

Column SK_ID_PREV: 0 null values

Column SK_ID_CURR: 0 null values

Column NAME_CONTRACT_TYPE: 0 null values

Column AMT_ANNUITY: 372235 null values

Column AMT_APPLICATION: 0 null values

Column AMT_CREDIT: 1 null values

Column AMT_DOWN_PAYMENT: 895844 null values

Column AMT_GOODS_PRICE: 385515 null values

Column WEEKDAY_APPR_PROCESS_START: 0 null values

Column HOUR_APPR_PROCESS_START: 0 null values

Column FLAG_LAST_APPL_PER_CONTRACT: 0 null values

Column NFLAG_LAST_APPL_IN_DAY: 0 null values

Column RATE_DOWN_PAYMENT: 895844 null values

Column RATE_INTEREST_PRIMARY: 1664263 null values

Column RATE_INTEREST_PRIVILEGED: 1664263 null values

Column NAME_CASH_LOAN_PURPOSE: 0 null values

Column NAME_CONTRACT_STATUS: 0 null values

Column DAYS_DECISION: 0 null values

Column NAME_PAYMENT_TYPE: 0 null values

Column CODE_REJECT_REASON: 0 null values

Column NAME_TYPE_SUITE: 820405 null values

Column NAME_CLIENT_TYPE: 0 null values

Column NAME_GOODS_CATEGORY: 0 null values

Column NAME_PORTFOLIO: 0 null values

Column NAME_PRODUCT_TYPE: 0 null values

Column CHANNEL_TYPE: 0 null values

Column SELLERPLACE_AREA: 0 null values

Column NAME_SELLER_INDUSTRY: 0 null values

Column CNT_PAYMENT: 372230 null values

Column NAME_YIELD_GROUP: 0 null values

Column PRODUCT_COMBINATION: 346 null values

Column DAYS_FIRST_DRAWING: 673065 null values

Column DAYS_FIRST_DUE: 673065 null values

Column DAYS_LAST_DUE_1ST_VERSION: 673065 null values

Column DAYS_LAST_DUE: 673065 null values

Column DAYS_TERMINATION: 673065 null values

Column NFLAG_INSURED_ON_APPROVAL: 673065 null values